behaviors:
  MoveToGoal:
    trainer_type: ppo
    network_settings:
      memory:
        memory_size: 256
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.1
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000